### ISSUE TITLE
Peer dependency issues

### ISSUE THREAD

**Issue by IanVS** [graphql-mocks/graphql-mocks#103]
While installing graphql-mocks and @graphql-mocks/network-msw, I got a peer dependency error from npm:

```
npm ERR! Found: graphql-mocks@0.8.0
npm ERR! node_modules/graphql-mocks
npm ERR!   dev graphql-mocks@"^0.8.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer graphql-mocks@"^0.7.2" from @graphql-mocks/network-msw@0.1.0
```

I can force the installation, but I wanted to let you know that the latest versions do not seem to match up correctly with each other.

**Comment by chadian** [comment]
#107 adds checks for testing packages against their peer dependencies. Turns out there quite a few that need a bump, so the next release should catch these and resolve compatibility issues. That pull request will also add passing new changes of package versions to the existing range so that there should be an ever-updating compatible range if tests pass. I will also call out breaking changes in PRs which get logged out while creating the release and assigned versions, hopefully these changes stabilize the versions across packages.

**Comment by chadian** [comment]
#107 #115 Improved the release process to take package's peer dependencies and test them against older versions, and include new versions being released. #108 Pull requests can now include change log entries to call out features, bugs and breaking changes which are reported while creating a release and choosing the appropriate version, along with breaking peer dependencies.

A set of releases just went out in #117 using the new scripts and it looks like everything went well. I'll keep an eye out for any issues but I think this is in a much better place now and versioning should be much more consistent.
