### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by DilLip-Chowdary-Codes** [graphql-mocks/graphql-mocks#205]
Steps to reproduce:

- [Create a React app](https://create-react-app.dev/docs/getting-started/).

```
npx create-react-app my-app
cd my-app
npm start
```
- Replace index.js and App.js with the file contents [here](https://gist.github.com/DilLip-Chowdary-Codes/8a5fbe99ada4ad5cd3328e7cc6ebc366).
- Run the below command to start the mock server.

```
npx gqlmocks serve --schema ~/Codes/graphql_app/schema.graphql --fake
```
- Set the generated endpoint [http://localhost:4444/graphql](http://localhost:4444/graphql) in App client.
- Start the app server.
```
npm start
```
and when I check my app in the browser, I'm getting the `CORS-Error`, screenshot is attached below.

![GraphQL CORS Error](https://user-images.githubusercontent.com/66238621/193506468-46ca2b07-3bf1-41c6-acee-090cac74cb70.png)

Are any existing ways to fix this?

**Comment by chadian** [comment]
Thanks for reporting and the reproduction steps! I think I know what's going on. The express app that gets stood up as part of this command is pretty basic and I think I know what needs to be changed. If you have time and want to dive in, it's likely somewhere in the [express setup here](https://github.com/graphql-mocks/graphql-mocks/blob/4bc76cca7bbe21644c6830faa3366fcd93fbbe50/packages/cli/src/commands/serve.ts#L100-L145), otherwise I'll try to get around to it in the next few weeks.

**Comment by DilLip-Chowdary-Codes** [comment]
Here is the [PR](https://github.com/graphql-mocks/graphql-mocks/pull/211) to fix this issue.
